#!/bin/bash

if [ ! -f grime ] ||
   [ Expression.hs -nt grime ] ||
   [ PrattParser.hs -nt grime ] ||
   [ Parser.hs -nt grime ] ||
   [ Matcher.hs -nt grime ] ||
   [ grime.hs -nt grime ]; then
   >&2 echo "Newer source files detected, compiling."
   >&2 ghc -O2 grime.hs
fi

./grime $*
